title: Hikvision Intercom RE
remote_theme: pages-themes/slate@v0.2.0
description: Deep-dive into a Hikvision intercom system.

exclude:
  - "*.bin"
  - "*.BIN"
  - TEMPLATE.md
  - report.css
  - TASKS.md
  - binary_blob_data.txt
  - strings_output.txt
